### ISSUE TITLE
Loaded OBJ does not show up ?

### ISSUE THREAD

**Issue by nyue** [ospray/ospray_studio#3] opened 2021-09-11 04:25 UTC
Hi,

  I loaded an obj (exported from blender3d) [the monkey.obj], it does not show up in the ospray_studio window.

  What am I doing wrong ?

Cheers

**Comment by BruceCherniak** [comment] 2021-09-13 14:31
Impossible to say without more information.  Are you able to display the simple demo scenes?  `file -> Demo scene -> tutorial_scene` ?

**Comment by BruceCherniak** [comment] 2021-09-22 15:58
This will likely be a duplicate of issue #2 that we're discussing.

**Comment by BruceCherniak** [comment] 2021-10-01 01:17
Having talked more in issue #2, this is definitely a duplicate of that.  Closing.

**Closed as completed by BruceCherniak** 2021-10-01 01:17 UTC
